services:
  - type: web
    name: hrms-app
    env: java
    plan: free
    buildCommand: "./mvnw clean package"  # or ./gradlew build
    startCommand: "java -jar target/hrms-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
